version: '2'
services:
  api:
    build: .
    entrypoint: sh ./docker-entrypoint.sh
    restart: unless-stopped
    volumes:
      - .:/opt/app
    ports:
      - "3333:3333"
    environment:
      PUBLIC_URL: './'
